### ISSUE TITLE
Typo error - package-lock.json gets its content from yarn.lock file

### ISSUE THREAD

**Issue by artem-khromov** [Apployees/apployees-nx#1]
There should be `rootPackageLockLockFilePath` instead.
https://github.com/Apployees/apployees-nx/blob/b0bf17cf04b0c39e728a9c46f7972f7c3a1a868e/libs/common-build-utils/src/lib/generate-package-json/all-deps-calculator.ts#L117

**Comment by atifsyedali** [comment]
Thanks @artem-khromov and @iteufel
