### ISSUE TITLE
Build process creates an invalid name for package.json file.

### ISSUE THREAD

**Issue by IO89** [Apployees/apployees-nx#4]
We have decided to use Apployees-nx plugin, which is great btw, to build our node application with separate `package.json` file. It crafts `name` key in `package.json` file that violates allowed pattern.

 For example, ```"name": "@<name-of-the-project>/<folder-of-app>/<name-of-the-app> "```.
In this case `@` and `/` are not allowed symbols in `package.json` file. I wonder would it be possible to override this behavior?

**Comment by IO89** [comment]
Update: Found out that we could specify our own name in `package.json`.

**Comment by atifsyedali** [comment]
Oh yea I came across that issue recently as well. Ended up overriding as you mentioned. I can probably do some name normalization to fit package.json criteria...
