### ISSUE TITLE
Can't figure out how to use webserver

### ISSUE THREAD

**Issue by BorisTB** [Apployees/apployees-nx#5]
At first it crashed on yarn add, when I switched to node v12 (was using v14 before) it was installed but when i run `nx g @apployees-nx/webserver:app myApp` it asks me `In which directory should the webserver application be generated` when i type anything i get an error `Cannot read property 'antd' of undefined`

**Comment by BorisTB** [comment]
Oh, I guess it's supposed to be customised by the project. Nevermind

**Comment by AveryCameronUofR** [comment]
what ended up being the fix for this? I'm trying to generate a new project to put an existing react app into and I'm running into the same issue

**Comment by atifsyedali** [comment]
Sorry haven't had the time to look into it. I am not getting any error. @BorisTB can you please share how you got it to work?
